  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="/">Home</a></li>
            <li><a href="store.php" >Store</a></li>
            <li><a href="support.php" >Support</a></li>
            <li><a href="contact.php" >Contact</a></li>
            <li><a href="user.php" >My Account</a></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

    
  <script src="js/vendor/jquery.js"></script>
  <script src="js/foundation.min.js"></script>
  <script>
    $(document).foundation();
  </script>
</body>
</html>