<div class="header_container">
  <div class="header_section">
    <div class="header large-3 columns">
      <h1 class="logo"><img src="http://placehold.it/400x100&text=WaterVPN Logo"/></h1>
    </div>
    <div class="nav large-9 columns">
      <ul class="right button-group">
        <li><a href="/" class="button">Home</a></li>
        <li><a href="store.php" class="button">Store</a></li>
        <li><a href="support.php" class="button">Support</a></li>
        <li><a href="contact.php" class="button">Contact</a></li>
        <li><a href="user.php" class="button">My Account</a></li>
      </ul>
    </div>
    <div class="clearfix"></div>
  </div>
</div>