<ul class="example-orbit" data-orbit>
  <li>
    <img src="http://placehold.it/1000x400&text=[ WaterVPN a tranparent VPN provider ]" />
    <div class="orbit-caption">
      We run this company like no others.
    </div>
  </li>
  <li class="active">
    <img src="http://placehold.it/1000x400&text=[ We located in Canada, and we like maple syrup and privacy.]" />
    <div class="orbit-caption">
      Go Maple syrup.
    </div>
  </li>
  <li>
    <img src="http://placehold.it/1000x400&text=[ Give us feedback, we are listening. ]" />
    <div class="orbit-caption">
      You feedback are important to us.
    </div>
  </li>
</ul>