<ul class="example-orbit" data-orbit>
  <li>
    <img src="http://placehold.it/1000x400&text=[ Slider image 1 ]" />
    <div class="orbit-caption">
      Caption One.
    </div>
  </li>
  <li class="active">
    <img src="http://placehold.it/1000x400&text=[ Slider image 2 ]" />
    <div class="orbit-caption">
      Caption Two.
    </div>
  </li>
  <li>
    <img src="http://placehold.it/1000x400&text=[ Slider image 3 ]" />
    <div class="orbit-caption">
      Caption Three.
    </div>
  </li>
</ul>